In [1]:

%load_ext autoreload
%autoreload 2

In [2]:
from src.common import *

M = np.arange(5*2).reshape((5,2))
C = np.arange(8)

x = np.concatenate((M.ravel(),C.ravel()))


a = Variable(M.shape)
b = Variable(8)
a.set_pos(0)
b.set_pos(np.prod(M.shape))

i = b[4]
i(x)

np.int64(4)

In [3]:
np.prod(M.shape)

np.int64(10)

In [4]:
p = a[0,:]
q = b[3:5]
hs = hstack((p,q, [3,4]))

In [15]:
C[3:5]

array([3, 4])

In [6]:
p(x)

array([0, 1])

In [17]:
import numpy as np

M = np.linspace(0, 10, 10, dtype=int)
shape = M.shape
a = Variable(10)
b = M.ravel()
b[a[2]], M[2]

(array([3, 5]), array([0, 1]), array([3, 4]))

In [3]:
[1,2,3,4,5] + [None]

[1, 2, 3, 4, 5, None]

In [2]:
a = [[1, 2, 3, 4, 5],
     [1, 2, 3, 4, 5],
     [1, 2, 3, 4, 5],]

In [5]:
import numpy as np

np.pad(a, mode='constant', pad_width=((0,0), (0,1)), constant_values=0)

array([[1, 2, 3, 4, 5, 0],
       [1, 2, 3, 4, 5, 0],
       [1, 2, 3, 4, 5, 0]])

In [22]:
m = 100
epsilon = 1e-8

m / e

10000000000.0

In [23]:
import math
from tqdm import tqdm
max_iterations = math.ceil(math.log10(m / epsilon))

t = 1
for i in tqdm(range(max_iterations)):
    # Your iteration logic here
    if t > m / epsilon:
        break
    t *= 10

100%|██████████| 10/10 [00:00<00:00, 188932.61it/s]
