In [1]:

%load_ext autoreload
%autoreload 2

In [2]:
from src.common import *

M = np.arange(5*2).reshape((5,2))
C = np.arange(8)

x = np.concatenate((M.ravel(),C.ravel()))


a = Variable(M.shape)
b = Variable(8)
a.set_pos(0)
b.set_pos(np.prod(M.shape))

i = b[4]
i(x)

np.int64(4)

In [3]:
np.prod(M.shape)

np.int64(10)

In [4]:
p = a[0,:]
q = b[3:5]
hs = hstack((p,q, [3,4]))

In [15]:
C[3:5]

array([3, 4])

In [6]:
p(x)

array([0, 1])

In [17]:
sum = p + q
sum(x), p(x), q(x)

(array([3, 5]), array([0, 1]), array([3, 4]))

In [3]:
[1,2,3,4,5] + [None]

[1, 2, 3, 4, 5, None]