In [43]:

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [44]:
import numpy as np

from src.constrained_min import InteriorPointSolver
from tests.examples import Quadratic, Linear
from src.unconstrained_min import Newton
from src.utils import show_function

In [45]:
ineq = [Linear(row) for row in -np.eye(3)]
f = Quadratic(np.eye(3)) + Linear([0,0,2]) + 1
x0 = np.array([0.1, 0.2, 0.7])
A = np.array([[1,1,1]])
b = np.array([1])

solver = InteriorPointSolver()
solver.solve(f, ineq, A, b, x0)

[1] x: [0.1 0.2 0.7], y: 2.94
[2] x: [0.38379594 0.38379594 0.23240812], y: 1.813428422427657
[3] x: [0.46492546 0.46492546 0.07014908], y: 1.5775304182382435
[4] x: [0.49523263 0.49523263 0.00953474], y: 1.5096711027678615
[5] x: [0.49950248 0.49950248 0.00099504], y: 1.500996522791573
[6] x: [4.99950025e-01 4.99950025e-01 9.99500380e-05], y: 1.500099965022978
[7] x: [4.99995000e-01 4.99995000e-01 9.99949984e-06], y: 1.500009999649827
[8] x: [4.99999500e-01 4.99999500e-01 9.99994989e-07], y: 1.5000009999964883
[9] x: [4.9999995e-01 4.9999995e-01 9.9999949e-08], y: 1.500000099999963
[10] x: [4.99999995e-01 4.99999995e-01 9.99999940e-09], y: 1.500000009999999
[11] x: [4.99999999e-01 4.99999999e-01 9.99999985e-10], y: 1.5000000009999996


{'x': array([5.00000000e-01, 5.00000000e-01, 9.99949768e-11]),
 'f': np.float64(1.5000000000999945),
 'iterations': 12,
 'history': [array([0.1 , 0.2 , 0.7 , 2.94]),
  array([0.38379594, 0.38379594, 0.23240812, 1.81342842]),
  array([0.46492546, 0.46492546, 0.07014908, 1.57753042]),
  array([0.49523263, 0.49523263, 0.00953474, 1.5096711 ]),
  array([4.99502481e-01, 4.99502481e-01, 9.95037642e-04, 1.50099652e+00]),
  array([4.99950025e-01, 4.99950025e-01, 9.99500380e-05, 1.50009997e+00]),
  array([4.99995000e-01, 4.99995000e-01, 9.99949984e-06, 1.50001000e+00]),
  array([4.99999500e-01, 4.99999500e-01, 9.99994989e-07, 1.50000100e+00]),
  array([4.9999995e-01, 4.9999995e-01, 9.9999949e-08, 1.5000001e+00]),
  array([4.99999995e-01, 4.99999995e-01, 9.99999940e-09, 1.50000001e+00]),
  array([4.99999999e-01, 4.99999999e-01, 9.99999985e-10, 1.50000000e+00]),
  array([5.00000000e-01, 5.00000000e-01, 9.99949768e-11, 1.50000000e+00])]}

In [46]:
f.dim

3

In [47]:
f = Quadratic(np.eye(3))
A = np.array([1,2,1])
b = 4
solver = Newton()
x0 = [0,2,0]
# x0 = [1,1,1]
solver.solve(f=f, x0=x0, A=A, b=b)


Solving Quadratic using Newton solver...
[Newton:0] x: [0, 2, 0], y: 4.0
[Newton:1] x: [0.66666667 1.33333333 0.66666667], y: 2.666666666666666
[Newton:2] x: [0.66666667 1.33333333 0.66666667], y: 2.666666666666666


('Newton',
 2,
 array([0.66666667, 1.33333333, 0.66666667]),
 np.float64(2.666666666666666),
 True,
 True)

In [48]:
x = np.array([1/3,1/3,1/3])

x = np.array([0.1, 0.2, 0.7])
f0 = x[0]**2+x[1]**2+(1+x[2])**2
phi = -np.sum(np.log(x))

In [49]:
f0 + phi

np.float64(7.2086979493668775)

In [50]:
f0

np.float64(2.9399999999999995)

In [51]:
f0 + None

TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

In [2]:
import numpy as np

M = np.linspace(0, 10, 10, dtype=int)
shape = M.shape
a = Variable(10)
b = M.ravel()
b[a[2]], M[2]

(np.int64(2), np.int64(2))

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.stack((a,b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
tuple([3])

(3,)

In [2]:
a.shape

(10,)

In [3]:
from src.common import *

a = Variable(3)
b = Variable(3)
c = Stack((a,b), axis=1)
c.shape

(3, 2)

In [10]:
a = [[1, 2, 3, 4, 5],
     [1, 2, 3, 4, 5],
     [1, 2, 3, 4, 5],]

In [17]:
import numpy as np

np.pad(a, mode='constant', pad_width=(0,1), constant_values=0)

array([[1, 2, 3, 4, 5, 0],
       [1, 2, 3, 4, 5, 0],
       [1, 2, 3, 4, 5, 0],
       [0, 0, 0, 0, 0, 0]])

In [22]:
m = 100
epsilon = 1e-8

m / e

10000000000.0

In [23]:
import math
from tqdm import tqdm
max_iterations = math.ceil(math.log10(m / epsilon))

t = 1
for i in tqdm(range(max_iterations)):
    # Your iteration logic here
    if t > m / epsilon:
        break
    t *= 10

100%|██████████| 10/10 [00:00<00:00, 188932.61it/s]
